# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: miru

before:
  hooks:
    - go mod tidy

builds:
  - id: miru
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kondanta/miru/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    main: .
    binary: miru

archives:
  - id: miru
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  algorithm: sha256
  split: true

dockers:
  - id: miru-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/kondanta/miru:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - id: miru-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/kondanta/miru:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - id: miru-armv7
    goos: linux
    goarch: arm
    goarm: "7"
    image_templates:
      - "ghcr.io/kondanta/miru:{{ .Tag }}-armv7"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: "ghcr.io/kondanta/miru:{{ .Tag }}"
    image_templates:
      - "ghcr.io/kondanta/miru:{{ .Tag }}-amd64"
      - "ghcr.io/kondanta/miru:{{ .Tag }}-arm64"
      - "ghcr.io/kondanta/miru:{{ .Tag }}-armv7"
  - name_template: "ghcr.io/kondanta/miru:latest"
    image_templates:
      - "ghcr.io/kondanta/miru:{{ .Tag }}-amd64"
      - "ghcr.io/kondanta/miru:{{ .Tag }}-arm64"
      - "ghcr.io/kondanta/miru:{{ .Tag }}-armv7"

release:
  mode: keep-existing

changelog:
  disable: true
