package downloader

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteNetscapeCookies parses a Cookie header value (e.g. copied from browser
// DevTools) and writes a Netscape-format cookies file at outPath. All cookies
// are written with the given domain (typically ".youtube.com").
// The file is written to a sibling temp path then atomically renamed so a
// concurrent yt-dlp invocation never observes a partial file.
func WriteNetscapeCookies(raw, domain, outPath string) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	f, err := os.CreateTemp(filepath.Dir(outPath), ".cookies-*.tmp")
	if err != nil {
		return fmt.Errorf("create cookies file: %w", err)
	}
	if err := f.Chmod(0o600); err != nil {
		_ = f.Close()
		_ = os.Remove(f.Name())
		return fmt.Errorf("set cookies file permissions: %w", err)
	}
	tmpPath := f.Name()

	w := bufio.NewWriter(f)
	for _, line := range []string{
		"# Netscape HTTP Cookie File",
		"# This file is generated by miru. Do not edit.",
		"",
	} {
		if _, err := fmt.Fprintln(w, line); err != nil {
			_ = f.Close()
			_ = os.Remove(tmpPath)
			return fmt.Errorf("write cookies header: %w", err)
		}
	}

	for pair := range strings.SplitSeq(raw, ";") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		name, value, _ := strings.Cut(pair, "=")
		name = strings.TrimSpace(name)
		value = strings.TrimSpace(value)
		if name == "" {
			continue
		}
		// Fields: domain  include_subdomains  path  secure  expiry  name  value
		// secure=TRUE: YouTube is HTTPS-only; cookies must not be sent over plain HTTP.
		// expiry=0 → session cookie; yt-dlp treats 0 as valid.
		if _, err := fmt.Fprintf(w, "%s\tTRUE\t/\tTRUE\t0\t%s\t%s\n", domain, name, value); err != nil {
			_ = f.Close()
			_ = os.Remove(tmpPath)
			return fmt.Errorf("write cookie %q: %w", name, err)
		}
	}

	if err := w.Flush(); err != nil {
		_ = f.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("flush cookies file: %w", err)
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close cookies file: %w", err)
	}
	if err := os.Rename(tmpPath, outPath); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("install cookies file: %w", err)
	}
	return nil
}
