package downloader

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteNetscapeCookies parses a Cookie header value (e.g. copied from browser
// DevTools) and writes a Netscape-format cookies file at outPath. All cookies
// are written with the given domain (typically ".youtube.com").
func WriteNetscapeCookies(raw, domain, outPath string) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create cookies file: %w", err)
	}
	defer func() { _ = f.Close() }()

	w := bufio.NewWriter(f)
	for _, line := range []string{
		"# Netscape HTTP Cookie File",
		"# This file is generated by miru. Do not edit.",
		"",
	} {
		if _, err := fmt.Fprintln(w, line); err != nil {
			return fmt.Errorf("write cookies header: %w", err)
		}
	}

	for pair := range strings.SplitSeq(raw, ";") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		name, value, _ := strings.Cut(pair, "=")
		name = strings.TrimSpace(name)
		value = strings.TrimSpace(value)
		if name == "" {
			continue
		}
		// Fields: domain  include_subdomains  path  secure  expiry  name  value
		// expiry=0 → session cookie; yt-dlp treats 0 as valid.
		if _, err := fmt.Fprintf(w, "%s\tTRUE\t/\tFALSE\t0\t%s\t%s\n", domain, name, value); err != nil {
			return fmt.Errorf("write cookie %q: %w", name, err)
		}
	}

	return w.Flush()
}
