package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

func cookiesCmd() *cobra.Command {
	var output, dataDir string

	cmd := &cobra.Command{
		Use:   "cookies COOKIE_HEADER",
		Short: "Write YouTube browser cookies to a Netscape-format file",
		Long: `Parse a Cookie header value copied from browser DevTools and write it to a
Netscape-format cookies file for use with MIRU_YTDLP_COOKIES_FILE.

How to get the Cookie header:
  1. Open YouTube in your browser and log in.
  2. Open DevTools → Network tab → reload the page.
  3. Click XHR to filter requests.
  4. Click any youtube.com request → Headers → find the "Cookie:" request header.
  5. Copy everything after "Cookie: " and pass it as the argument to this command.

Example:
  miru cookies "VISITOR_INFO1_LIVE=abc; SID=def; ..."`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if dataDir == "" {
				dataDir = os.Getenv("MIRU_DATA_DIR")
			}
			if output == "" {
				if dataDir == "" {
					return fmt.Errorf("--output is required when MIRU_DATA_DIR is not set")
				}
				output = filepath.Join(dataDir, "cookies.txt")
			}

			raw := strings.TrimPrefix(args[0], "Cookie: ")
			if err := writeNetscapeCookies(raw, ".youtube.com", output); err != nil {
				return err
			}
			fmt.Printf("cookies written to %s\n", output)
			fmt.Printf("set MIRU_YTDLP_COOKIES_FILE=%s\n", output)
			return nil
		},
	}

	cmd.Flags().StringVar(&output, "output", "",
		"output file path (default: <data-dir>/cookies.txt)")
	cmd.Flags().StringVar(&dataDir, "data-dir", "",
		"miru data directory (overrides MIRU_DATA_DIR; used to derive default output path)")

	return cmd
}

// writeNetscapeCookies parses a Cookie header value and writes a Netscape-format
// cookies file. All cookies are written with the given domain.
func writeNetscapeCookies(raw, domain, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create cookies file: %w", err)
	}
	defer func() { _ = f.Close() }()

	w := bufio.NewWriter(f)
	lines := []string{
		"# Netscape HTTP Cookie File",
		"# This file is generated by miru. Do not edit.",
		"",
	}
	for _, line := range lines {
		if _, err := fmt.Fprintln(w, line); err != nil {
			return fmt.Errorf("write cookies header: %w", err)
		}
	}

	for pair := range strings.SplitSeq(raw, ";") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		name, value, _ := strings.Cut(pair, "=")
		name = strings.TrimSpace(name)
		value = strings.TrimSpace(value)
		if name == "" {
			continue
		}
		// Fields: domain  include_subdomains  path  secure  expiry  name  value
		// expiry=0 → session cookie; yt-dlp treats 0 as valid.
		if _, err := fmt.Fprintf(w, "%s\tTRUE\t/\tFALSE\t0\t%s\t%s\n", domain, name, value); err != nil {
			return fmt.Errorf("write cookie %q: %w", name, err)
		}
	}

	return w.Flush()
}
